Initial commit
ichiro-its/ninshiki_yolo pull request #1
Opened 2021-08-17 12:31 UTC by Nathan24zz

Initial commit

2021-08-17 12:35 UTC, segara2410 requested changes

2021-08-17 12:35 UTC, segara2410 commented on .gitignore
> +*.weights
Add a newline at the end of the file.

2021-08-17 12:35 UTC, segara2410 commented on ninshiki_yolo/detector.py
> +    def __init__(self, node_name, topic_name, config, names, weights):
Add type hint for function parameters and return value

2021-08-18 11:26 UTC, threeal requested changes
See individual comment for the requested changes.

2021-08-18 11:26 UTC, threeal commented on README.md
> +[![build and test status](https://github.com/ichiro-its/ninshiki/actions/workflows/build-and-test.yml/badge.svg)](https://github.com/ichiro-its/ninshiki/actions)
The `build-and-test` workflow doesn't exist, yet you already add badge for it.

2021-08-18 11:26 UTC, threeal commented on package.xml
> +  <version>0.0.0</version>
I actually prefer to start project's version from `0.1.0`, but it's actually fine to use that.

2021-08-18 11:26 UTC, threeal commented on package.xml
> +  <exec_depend>ninshiki_interface</exec_depend>
what is `ninshiki_interface` used for?

2021-08-18 13:01 UTC, threeal approved these changes
Looks good to me.

2021-08-18 13:03 UTC, segara2410 approved these changes
lgtm

2021-08-18 13:40 UTC, merged